reg/urls.py
from django.urls import path
from .views import index

app_name = 'reg'

urlpatterns = [
    path('', index, name='index'),
]

reg_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('reg.urls', namespace='reg')),
    path('admin/', admin.site.urls),
]

reg/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Person(models.Model):
	full_name = models.CharField(max_length=255)
	phone_number = PhoneNumberField()

reg/forms.py
from django import forms
from .models import Person
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class PersonForm(forms.ModelForm):
	full_name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
	phone_number = PhoneNumberField(
		widget = PhoneNumberPrefixWidget(initial = "UZ", attrs={"class":"form-control"}),

	)

	class Meta:
		model = Person
		fields = "__all__"
		

reg/views.py
from django.shortcuts import render
from .forms import PersonForm


def index(request):
	if request.method == "POST":
		form = PersonForm(request.POST)
		if form.is_valid():
			form.save()
			msm = "Ishladi"
		else:
			return render(request, 'reg/landing.html', locals())

	form = PersonForm()
	return render(request, 'reg/landing.html', locals())

templates/reg/_landing.html
{% load static %} 
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Online test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"/>
    <meta name="description" content="Badges and labels are used to offer extra small pieces of info for your content.">
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">
	<link href="{% static 'main.css' %}" rel="stylesheet">
</head>
<body>
	<div class="app-container app-theme-white body-tabs-shadow fixed-header fixed-sidebar">
		<div class="app-header header-shadow">
			<div class="app-header__logo">
		        <a href="{% url 'landing:landing' %}" style="background: none; height: 40px; width: 150px;" class="logo-src mb-2 mr-2 btn-icon btn-icon-only btn-shadow btn-dashed btn btn-outline-info">
		        	<i class="pe-7s-science btn-icon-wrapper"> 13 MAKTAB </i>
		        </a>
			    <div class="header__pane ml-auto">
					<button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
			        	<span class="hamburger-box">
			            	<span class="hamburger-inner"></span>
						</span>
			        </button>
			    </div>
			</div>
			<!-- header menu -->
			<div class="app-header__content">
				<div class="app-header-left">
			    	<div class="search-wrapper">
			        	<div class="input-holder">
			            	<input type="text" class="search-input" placeholder="Qidirish">
			            	<button class="search-icon"><span></span></button>
			            </div>
			        	<button class="close"></button>
			        </div>
				</div>
				<div class="app-header-right">
			        <!-- Tilni tanlash -->
			    	<!-- <div class="header-dots">
			            <div class="dropdown">
			            	<button type="button" data-toggle="dropdown" class="p-0 mr-2 btn btn-link">
			                	<span class="icon-wrapper icon-wrapper-alt rounded-circle">
			                    	<span class="icon-wrapper-bg bg-focus"></span>
			                        <span class="language-icon opacity-8 flag large uz"></span>
			                    </span>
			            	</button>
							<div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu dropdown-menu-right">
			                	<div class="dropdown-menu-header">
			                    	<div class="dropdown-menu-header-inner pt-4 pb-4 bg-focus">
			                        	<div class="menu-header-image opacity-70" style="background-image: url('assets/images/dropdown-header/city3.jpg');"></div>
			                            <div class="menu-header-content text-center text-white">
			                            	<h6 class="menu-header-subtitle mt-0"> Tilni o'zgartirish </h6>
					                    </div>
			                        </div>
								</div>
			                    <h6 tabindex="-1" class="dropdown-header"> Joriy til </h6>
						        <button type="button" tabindex="0" class="dropdown-item">
				                    <span class="mr-3 opacity-8 flag large UZ"></span> UZ
		                        </button>
			                    <h6 tabindex="-1" class="dropdown-header"> Boshqa til </h6>
			                    <a href="#">
				                    <button type="button" tabindex="0" class="dropdown-item">
				                    	<span class="mr-3 opacity-8 flag large RU"></span> RU
				                	</button>
			                    </a>
			                </div>
			            </div>
			        </div> -->
			        <!-- end tilni tanlash -->
			        <!-- Login -->
			        <div class="header-btn-lg pr-0">
			        	<div class="widget-content p-0">
			            	<div class="widget-content-wrapper">
			                	<div class="widget-content-left">
			                    	<div class="btn-group">
			                        	<a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
			                            	<img width="42" class="rounded-circle" src="{% static 'assets/images/avatars/nophoto.png' %}" alt="nophoto.png">
			                                <i class="fa fa-angle-down ml-2 opacity-8"></i>
			                        	</a>
			                            <div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu-lg dropdown-menu dropdown-menu-right">
			                            	<div class="dropdown-menu-header">
			                                	<div class="dropdown-menu-header-inner bg-info">
			                                    	<div class="menu-header-image opacity-2" style="background-image: url({% static 'assets/images/dropdown-header/city3.jpg' %});"></div>
			                                        <div class="menu-header-content text-left">
			                                            <div class="widget-content p-0">
			                                                <div class="widget-content-wrapper">
			                                                   	<div class="widget-content-left mr-3">
			                                                        <img width="42" class="rounded-circle" src="{% static 'assets/images/avatars/nophoto.png' %}" alt="">
			                                                    </div>
			                                            		<div class="widget-content-left">
			                                                       	<div class="widget-heading">
			                                                       		fio
			                                                       	</div>
			                                                        <div class="widget-subheading opacity-8">
			                                                            13-maktabning 7-sinf o'quvchisi
			                                                        </div>
			                                                    </div>
			                                                    <div class="widget-content-right mr-2">
			                                                        <a href="#" class="btn-pill btn-shadow btn-shine btn btn-focus"> Chiqish </a>
			                                                    </div>
			                                                </div>
			                                            </div>
		                                            </div>
		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		            <!-- end login -->
		        </div>
			</div>
			<!-- end header menu -->
		</div>
	    <div class="app-main">
	        {% include './menu.html' %}
	        <div class="app-main__outer">
	            <div class="app-main__inner">
	                <div class="tab-content">
	                        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
	                            <div class="row">
	                                <div class="col-lg-12">
	                                    <div class="main-card mb-3 card">
	                                        <div class="card-body"><h5 class="card-title">Test o'tkazish uchun mavjud fanlar</h5>
	                                            <div class="row">
			                                        <div class="col-sm-4 col-xl-3">
			                                            <a href="#">
				                                            <button class="btn-icon-vertical mb-3 btn-transition btn-block btn btn-outline-primary">
				                                                <i class="lnr-license btn-icon-wrapper"></i>
				                                                <span class="badge badge-primary badge-dot badge-dot-lg badge-dot-lg badge-dot-inside"></span>
				                                                fan_nomi
				                                            </button>
				                                        </a>
			                                        </div>
	                                            </div>
	                                        </div>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
	<script type="text/javascript" src="{% static 'assets/scripts/main.js' %}"></script>
</body>
</html>

templates/reg/header.html
<div class="app-header header-shadow">
	<div class="app-header__logo">
        <a href="{% url 'landing:landing' %}" style="background: none; height: 40px; width: 150px;" class="logo-src mb-2 mr-2 btn-icon btn-icon-only btn-shadow btn-dashed btn btn-outline-info">
        	<i class="pe-7s-science btn-icon-wrapper"> 13 MAKTAB </i>
        </a>
	    <div class="header__pane ml-auto">
			<button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
	        	<span class="hamburger-box">
	            	<span class="hamburger-inner"></span>
				</span>
	        </button>
	    </div>
	</div>
	<!-- header menu -->
	<div class="app-header__content">
		<div class="app-header-left">
	    	<div class="search-wrapper">
	        	<div class="input-holder">
	            	<input type="text" class="search-input" placeholder="Qidirish">
	            	<button class="search-icon"><span></span></button>
	            </div>
	        	<button class="close"></button>
	        </div>
		</div>
		<div class="app-header-right">
	        <!-- Tilni tanlash -->
	    	<!-- <div class="header-dots">
	            <div class="dropdown">
	            	<button type="button" data-toggle="dropdown" class="p-0 mr-2 btn btn-link">
	                	<span class="icon-wrapper icon-wrapper-alt rounded-circle">
	                    	<span class="icon-wrapper-bg bg-focus"></span>
	                        <span class="language-icon opacity-8 flag large uz"></span>
	                    </span>
	            	</button>
					<div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu dropdown-menu-right">
	                	<div class="dropdown-menu-header">
	                    	<div class="dropdown-menu-header-inner pt-4 pb-4 bg-focus">
	                        	<div class="menu-header-image opacity-70" style="background-image: url('assets/images/dropdown-header/city3.jpg');"></div>
	                            <div class="menu-header-content text-center text-white">
	                            	<h6 class="menu-header-subtitle mt-0"> Tilni o'zgartirish </h6>
			                    </div>
	                        </div>
						</div>
	                    <h6 tabindex="-1" class="dropdown-header"> Joriy til </h6>
				        <button type="button" tabindex="0" class="dropdown-item">
		                    <span class="mr-3 opacity-8 flag large UZ"></span> UZ
                        </button>
	                    <h6 tabindex="-1" class="dropdown-header"> Boshqa til </h6>
	                    <a href="#">
		                    <button type="button" tabindex="0" class="dropdown-item">
		                    	<span class="mr-3 opacity-8 flag large RU"></span> RU
		                	</button>
	                    </a>
	                </div>
	            </div>
	        </div> -->
	        <!-- end tilni tanlash -->
	        <!-- Login -->
	        <div class="header-btn-lg pr-0">
	        	<div class="widget-content p-0">
	            	<div class="widget-content-wrapper">
	                	<div class="widget-content-left">
	                    	<div class="btn-group">
	                        	<a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
	                            	<img width="42" class="rounded-circle" src="{% static 'assets/images/avatars/nophoto.png' %}" alt="nophoto.png">
	                                <i class="fa fa-angle-down ml-2 opacity-8"></i>
	                        	</a>
	                            <div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu-lg dropdown-menu dropdown-menu-right">
	                            	<div class="dropdown-menu-header">
	                                	<div class="dropdown-menu-header-inner bg-info">
	                                    	<div class="menu-header-image opacity-2" style="background-image: url({% static 'assets/images/dropdown-header/city3.jpg' %});"></div>
	                                        <div class="menu-header-content text-left">
	                                            <div class="widget-content p-0">
	                                                <div class="widget-content-wrapper">
	                                                   	<div class="widget-content-left mr-3">
	                                                        <img width="42" class="rounded-circle" src="{% static 'assets/images/avatars/nophoto.png' %}" alt="">
	                                                    </div>
	                                            		<div class="widget-content-left">
	                                                       	<div class="widget-heading">
	                                                       		fio
	                                                       	</div>
	                                                        <div class="widget-subheading opacity-8">
	                                                            13-maktabning 7-sinf o'quvchisi
	                                                        </div>
	                                                    </div>
	                                                    <div class="widget-content-right mr-2">
	                                                        <a href="{% url logout %}" class="btn-pill btn-shadow btn-shine btn btn-focus"> Chiqish </a>
	                                                    </div>
	                                                </div>
	                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end login -->
        </div>
	</div>
	<!-- end header menu -->
</div>

templates/reg/landing.html
{% load static %} 
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Register - Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"
    />
    <meta name="description" content="HTML Bootstrap 4 Dashboard Template">

    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <link href="{% static 'main.css' %}" rel="stylesheet">
</head>

<body>
<div class="app-container app-theme-white body-tabs-shadow">
        <div class="app-container">
            <div class="h-100">
                <div class="h-100 no-gutters row">
                    <div class="h-100 d-md-flex d-sm-block bg-white justify-content-center align-items-center col-md-12 col-lg-7">
                        <div class="mx-auto app-login-box col-sm-12 col-md-10 col-lg-9">
                            <div class="app-logo"></div>
                            <h4> {{ msm }}

                                <div>Welcome,</div>
                                <span>Lorem ipsum dolor sit amet <span class="text-success">few seconds</span> sunt in culpa qui officia deserunt mollit anim id est laborum.</span></h4>
                            <div>
                                <form class="" method="post" action=" {% url 'reg:index' %} "> {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="position-relative form-group">
                                                <label for="exampleEmail" class="">
                                                    <span class="text-danger">*</span> Phone number
                                                </label>
                                                {{form.phone_number}}
{#                                                <input name="phone_number" id="exampleEmail" placeholder="(xy) zzz zz zz" type="phone" class="form-control">#}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="position-relative form-group">
                                                <label for="exampleName" class="">
                                                    <span class="text-danger">*</span> Name
                                                </label>
                                                {{form.full_name}}
{#                                                <input name="full_name" id="exampleName" placeholder="Andrey Arshavin" type="text" class="form-control">#}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-4 d-flex align-items-center">
                                        <div class="ml-auto">
                                            <button class="btn-wide btn-pill btn-shadow btn-hover-shine btn btn-primary btn-lg">Register</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="d-lg-flex d-xs-none col-lg-5">
                        <div class="slider-light">
                            <div class="slick-slider slick-initialized">
                                <div>
                                    <div class="position-relative h-100 d-flex justify-content-center align-items-center bg-premium-dark" tabindex="-1">
                                        <div class="slide-img-bg" style="background-image: url({% static 'assets/images/originals/citynights.jpg' %});"></div>
                                        <div class="slider-content"><h3>Text1, Text2, Text3</h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
    <script type="text/javascript" src="{% static 'assets/scripts/main.js' %}"></script>
</body>

</html>

templates/reg/menu.html
{% load static %}
<div class="app-sidebar sidebar-shadow">
	<!-- Menu -->
	<div class="scrollbar-sidebar">
		<div class="app-sidebar__inner">
			<ul class="vertical-nav-menu">
				<li class="app-sidebar__heading">Menu</li>
				<li>
					<a href="#">
						<i class="metismenu-icon pe-7s-rocket"></i>Testni boshlash
						<i class="metismenu-state-icon pe-7s-angle-right caret-left"></i>
					</a>
	            </li>
	            <li>
	               	<a href="#">
		                <i class="metismenu-icon pe-7s-browser"></i>Reyting
		                <i class="metismenu-state-icon pe-7s-angle-right caret-left"></i>
		            </a>
	            </li>
	            <li>
	                <a href="#">
	               		<i class="metismenu-icon pe-7s-plugin"></i> Shaxsiy kabinet
	                   	<i class="metismenu-state-icon pe-7s-angle-right caret-left"></i>
	               	</a>
	           	</li>
	            <li class="">
                    <a href="#" aria-expanded="false">
                        <i class="metismenu-icon lnr-screen"></i>
                        	Test qo'shish
                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                    </a>
                    <ul class="mm-collapse" style="height: 7.04px;">
                        <li>
                            <a href="test_plus.php">
                                <i class="metismenu-icon"></i>
                                Fayldan yuklash
                                <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                            </a>    
                        </li>
                        <li>
                            <a href="add_test.php">
                                <i class="metismenu-icon"></i>
                                Formula kiritish
                            </a>
                        </li>
                    </ul>
                </li>
	            <li>
	              	<a href="#">
	               		<i class="metismenu-icon lnr-users "></i> Foydalanuvchi qo'shish
	                   	<i class="metismenu-state-icon pe-7s-angle-right caret-left"></i>
	               	</a>
	            </li>
	        </ul>
	    </div>
	</div>
	<!-- end menu -->
</div>